restart-times: 0
jobscript: slurm_jobscript.sh
executor: cluster-generic
cluster-generic-submit-cmd: bw_submit.py
cluster-generic-status-cmd: bw_status.py
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 50
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 240
jobs: 50
keep-going: True
rerun-incomplete: True
# note that the space before the -- is necessary - otherwise cluster
# execution failes as --cleanenv gets interpreted as a new option since
# snakemake passes this on as --singularity-args "--cleanenv" - i.e. without
# a `=`
singularity-args: " --cleanenv"
